### ISSUE TITLE
Iteration plan for October-December 2020

### ISSUE THREAD

**Issue by nastushalk** [siberianmh/siberianmh#34]
This plan covers the work from October until the end of December.

For more understanding of how we cover the Iteration Plans, you can read in the [documentation](https://github.com/siberianmh/siberianmh/blob/master/docs/process/iteration-plan.md).

## Dates

- **November 6-November 9**: Plan rechecking and reorganization
- **November 30-December 1**: Plan rechecking and reorganization
- **December 25**: Endgame
- **January 14**: Drafting a new iteration plan

## Plan Items

Below is a summary of the top-level plan items.

Legend of annotations:

| Mark | Description                                       |
| ---- | ------------------------------------------------- |
| 🏃‍♂️   | work in progress                                  |
| ✋   | blocked task                                      |
| 💪   | stretch goal for this iteration                   |
| 🔴   | missing issue reference                           |
| 🔵   | more investigation required to remove uncertainty |
| ⚫   | under discussion within the team                  |

## Roads

- 💪 Make Roads ready for usage product on lower-orbit
- [x] Produce ready-to-use docker image for Roads #32
- API
	- [ ] Create simple public API #15
	- [ ] Node.js API Wrapper #33 
- [ ] Documentation #31 
- [ ] Add `GitLab` provider #17 
- [x] Implement `synchorize` event for `GitHub` provider #14

## Ozark

- [ ] Documentation #30 

## Uwulectron

- [x] Opensourcing #44 
- [ ] Add ability to give thanks the helper #118 

## Arcadia

- Nothing

## NPM Packages

- Nothing
